urls.py
from django.urls import path

from . import views

app_name = 'poll'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='details'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

models.py
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'poll/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'poll/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'poll/results.html'

def vote(request, question_id):
	question = get_object_or_404(Question, pk=question_id)
	try:
	    selected_choice = question.choice_set.get(pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
	    # Redisplay the question voting form.
	    return render(request, 'poll/detail.html', {
	        'question': question,
	        'error_message': "You didn't select a choice.",
	    })
	else:
	    selected_choice.votes += 1
	    selected_choice.save()
	return HttpResponseRedirect(reverse('poll:results', args=(question.id,)))

templates/poll/base.html
<!DOCTYPE html>
<html>
<head>
	<title>Poll App</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
</head>
<body>
	<div>
		<nav class="navbar navbar-dark bg-dark">
			<a class="navbar-brand" href="#">Polling App</a>
		</nav>
	</div>
	<div>
		{% block content %}{% endblock %}
	</div>
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>

templates/poll/detail.html
{% extends "poll/base.html" %}
{% block content %}
		<h2>{{ question.question_text }}</h2>
	<div class="d-flex p-2">

		{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

		<form action="{% url 'poll:vote' question.id %}" method="post">
		{% csrf_token %}
		{% for choice in question.choice_set.all %}
		    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
		    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
		{% endfor %}
		<input type="submit" value="Vote" class="btn btn-primary">
		</form>
	</div>
{% endblock content %}

templates/poll/index.html
{% extends "poll/base.html" %}
{% block content %}
		<div class="d-flex p-2">
			{% if latest_question_list %}
			    <ul class="list-group">
			    {% for question in latest_question_list %}
			        <li class="list-group-item"><a href="{% url 'poll:details' question.id %}">{{ question.question_text }}</a></li>
			    {% endfor %}
			    </ul>
				{% else %}
			    <p>No polls are available.</p>
			{% endif %}
		</div>
{% endblock content %}

templates/poll/results.html
{% extends "poll/base.html" %}
{% block content %}
	<h1>{{ question.question_text }}</h1>

	<ul>
	{% for choice in question.choice_set.all %}
	    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
	{% endfor %}
	</ul>

	<a href="{% url 'poll:details' question.id %}">Vote again?</a>
{% endblock content %}

templates/poll/vote.html
{% extends "poll/base.html" %}
{% block content %}
		<h2>You're voting for question {{ question_id }}</h2>
{% endblock content %}